### PR TITLE
Repeat fix 2

### LINKED ISSUE #157: `repeat` is not efficient on GPU
The ViT implementation contains  `repeat`, which will not work well for GPUs (due to scalar indexing)

https://github.com/FluxML/Metalhead.jl/blob/792076f1f86fdf713e2240cc0337c37ffd24fd1c/src/layers/embeddings.jl#L63

An alternative way to simulate repeat with broadcasting

https://github.com/avik-pal/Lux.jl/blob/49b69c7ed21ccde6fc8c07bacaf738de0b6fe497/lib/Boltz/src/vit.jl#L72

### PR DESCRIPTION
**Pull request by theabhirath**
Supersedes (closes) #158 since I messed up the commits a bit there. Also closes #157.

### CODE REVIEW

File: src/other/mlpmixer.jl [hunk 1]
```diff
@@ -132,7 +132,7 @@ return Chain(SkipConnection(Chain(Flux.Scale(planes),
                                   LayerScale(planes, λ),
                                   DropPath(drop_path_rate)), +),
              SkipConnection(Chain(Flux.Scale(planes),
-                                  mlp_layer(planes, Int(mlp_ratio * planes); dropout, activation),
+                                  mlp_layer(planes, Integer(mlp_ratio * planes); dropout, activation),
```
Comment (darsnack) [inline src/other/mlpmixer.jl:135]:
```suggestion
                                  mlp_layer(planes, Int(mlp_ratio * planes); dropout, activation),
```

Comment (theabhirath) [reply src/other/mlpmixer.jl:135]: Yikes, seem to have missed that

**Review by darsnack — APPROVED** [review]
